config/routes.rb
Rails.application.routes.draw do
  # Devise is used for logins & user mangement.
  devise_for :users
  # All page logic it can also be found by running rails routes to see full routing
  root to: 'pages#home'
  get '/journey', to: 'pages#journey', as: 'journey'
  get '/trips/:trip_id/itinerary', to: 'trips#itinerary', as: 'itinerary'
  patch '/trips/:trip_id/update_all', to: 'trip_dayts#update_all', as: "update_all_trip_dayts"
  get '/mydayts', to: 'dayts#mydayts', as: 'mydayts'
  get '/tagged', to: "dayts#tagged", as: :tagged
  patch '/trip_dayt/:id/remove', to: 'trip_dayts#remove', as: 'remove_trip_dayt'
  # get '/dayts/:trip_id', to: 'trip_dayts#save_extended_card', as: 'save_extended_card'

# Nested dayts, trip dayts & mass reviews as they all belong to a trip.
  resources :trips, only: [:new, :create, :show, :update, :index, :destroy] do
    resources :dayts, only: [:index]
    resources :trip_dayts, only: [:create]
    resources :mass_reviews, only: [:new, :create]
  end

  resources :dayts, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :trip_dayts, only: [:delete]

end

app/models/trip.rb
class Trip < ApplicationRecord
  attr_accessor :search_tags

  belongs_to :user, optional: true
  has_many :trip_dayts, dependent: :destroy

  has_many :dayts, through: :trip_dayts
  has_many :reviews, -> { distinct }, through: :trip_dayts

  # Standard validations for creation of a trip
  validates :title, presence: true
  validates :location, presence: true
  validates :distance, presence: true
  validates :date, presence: true
  accepts_nested_attributes_for :reviews

  acts_as_taggable_on :tags

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  # This controller contains the logic for the trips, sorting & viewing of trips.
  skip_before_action :authenticate_user!, only: [:new, :create, :itinerary]
  
  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_dayts_path(@trip)
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def index
    @next_trips = Trip.where(user_id: current_user, date: Date.today..).order(date: :desc)
    @past_trips = Trip.where(user_id: current_user, date: ...Date.today).order(date: :desc)
  end

  def show
    @trip = Trip.find(params[:id])
    # This is when dayts have been accepted to create te trip.
    @dayts = Dayt.includes(trip_dayts: :trip).where(trip_dayts: { status: "accepted", trip: @trip })
    # This orders the dayts by tripdayt and orders them using the hidden table found on the organise page
    @trip_dayts = @trip.trip_dayts.where(status: "accepted").order(:order)
    unless @dayts.empty?
      @markers = @dayts.geocoded.map do |dayt|
        {
          lat: dayt.latitude,
          lng: dayt.longitude,
          info_window: render_to_string(partial: "shared/info_window", locals: { dayt: dayt }),
          map_marker: render_to_string(partial: "shared/map_marker", locals: { dayt: dayt })
        }
      end
    end
  end

  def itinerary
    @trip = Trip.find(params[:trip_id])
    @dayts = Dayt.includes(trip_dayts: :trip).where(trip_dayts: { status: "accepted", trip: @trip })
    @trip_dayts = @trip.trip_dayts.where(status: "accepted")
    # @total_time = @dayts.sum(:duration).to_f
    unless @dayts.empty?
      @markers = @dayts.geocoded.map do |dayt|
        {
          lat: dayt.latitude,
          lng: dayt.longitude,
          info_window: render_to_string(partial: "shared/info_window", locals: { dayt: dayt }),
          map_marker: render_to_string(partial: "shared/map_marker", locals: { dayt: dayt })
        }
      end
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :location, :distance, :date, tag_list: [])
  end
end

app/views/trips/_trip.html.erb
  <%= link_to trip_path(trip), class: 'trip-link' do %>
  <div class="card-trip shadow" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= trip.dayts.first ? trip.dayts.first.photos.first.url : 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1635&q=80' %>)">
    <h3><%= trip.title %></h3>
    <h3><%= trip.date.strftime('%-d %b %Y') %></h3>
  </div>
  <% end %>

app/views/trips/index.html.erb
<div class="container px-4 trips">
  <h1 class="text-center pt-3 m-0">Upcoming Trips</h1>
  <% if @next_trips.empty? && @past_trips.empty? %>
    <h3 class='text-notice'>
      Looks like theres nothing here, select create a Trip to get started!
    </h3>
  <% end %>
  <div>
    <% @next_trips.each do |trip| %>
      <%= render 'trip', trip: trip %>
    <% end %>
  </div>
  <h1 class="text-center pt-3 m-0">Past Trips</h1>
    <% @past_trips.each do |trip| %>
      <%= render 'trip', trip: trip %>
    <% end %>
</div>
<footer>
  <%= link_to 'New Trip', new_trip_path, class: "btn next-btn" %>
</footer>

app/views/trips/itinerary.html.erb
<div data-controller='show-hide'>
  <div data-controller="sortable paralax-reset">
    <div class="slider-container" id="slider-container-itinerary">
      <div class="slider" data-show-hide-target="slider">

        <div class="slidee container text-center">
          <div class="organise-header">
            <%= link_to trip_dayts_path(@trip) do %>
              <i class="fa-solid fa-plus"></i>
            <% end %>
            <h1>Organise Your Trip</h1>
            <p>DRAG to change your schedule</p>
          </div>

          <%= render "shared/organise", trip: @trip %>
        </div>

        <div class="slidee slidee-map">
          <%= render "shared/hidden_mapbox" %>
        </div>

      </div>
    </div>
    <footer style="position: fixed; bottom: 0; height: 106px; display: grid; grid-template-columns: 1fr 1fr;">
        <button class='btn map-btn btn-width map_organise_trip' data-action='click->show-hide#toggle'>Map</button>
        <%# link_to "Confirm", trip_path(@trip), class: "btn next-btn btn-width" %>
      <%= form_with url: update_all_trip_dayts_path(@trip), method: :patch, id: "order-calendar-form" do |f| %>
        <% @trip_dayts.order(:order).each do |dayt| %>
          <%= f.text_field "dayt_ids[]", id: nil, data: { sortable_target: "input"}, value: dayt.id, class: "opacity-0 pe-none" %>
        <% end %>
        <%= f.submit class: "btn next-btn btn-width", id: "dayt-order-form-btn", style:"position: absolute; top: 9px; right: -32%; border: none; height: 66px" %>
      <% end %>
    </footer>
    <%# <footer> %>
      <%# <button class='btn map-btn btn-width' data-action='click->show-hide#toggle'>Map</button> %>
      <%# link_to "Confirm", trip_path(@trip), class: "btn next-btn btn-width" %>
    <%# </footer> %>
  </div>

</div>

app/views/trips/new.html.erb
<div class= "preferences" data-controller="index">
  <div class='container'>
    <h1 class="text-center pt-4">My Preferences</h1>
    <div class='pre-form' data-controller='flatpickr'>
      <%= simple_form_for @trip, html: { class: 'w-100' } do |f| %>
        <h2 class="text-center preference-titles">Trip Name?</h2>
        <%= f.input :title, label: false, placeholder: "Name of my trip", input_html: { class: "text-center trip-name" } %>

        <h2 class="text-center preference-titles">Where?</h2>
        <%= f.input :location, label: false, placeholder: "City",
            input_html: { data: { geocoder_target: "location" }, class: "d-none" },
            wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>

        <h2 class="text-center preference-titles">When?</h2>
              <%= f.input :date, as: :string, label: false, placeholder: "Today", required: false, input_html: {class: "datepicker text-center"} %>

        <h2 class="text-center preference-titles">Travel Distance?</h2>
        <%= f.input :distance, label: false, input_html: { class: "text-center " }, collection: User::DISTANCE do %>
        <%= f.select :distance, User::DISTANCE_KM, include_blank: 'How far do you want to travel' %>
        <% end %>


        <p class="text-center preference-titles">My interests</p>
        <%= render 'layouts/tags', f: f %>

        <%# <h3>125 Dayts found</h3> %>
        <footer>
          <%= f.submit class: "btn next-btn waves" %>
        </footer>

        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div>
  <div class="slider-container" data-controller="show-hide">
    <div class="slider" data-show-hide-target="slider">

      <div class="slidee container">
          <div class="organise-header">
            <%= link_to itinerary_path(@trip) do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <h1 class='pt-3 head-trip' style='text-center'><%= @trip.title %></h1>
          </div>
          <div data-show-hide-target='container'>
          <div class="row justify-content-end" id="calendar-container">
          <div class="calendar col-2 d-flex flex-column justify-content-between align-items-center">
            <p>8am</p>
            <p>9am</p>
            <p>10am</p>
            <p>11am</p>
            <p>12pm</p>
            <p>1pm</p>
            <p>2pm</p>
            <p>3pm</p>
            <p>4pm</p>
            <p>5pm</p>
          </div>


          <div class="col-10" data-controller='paralax'>
            <ul id="hello-list"  class="h-100 a-style">
              <% @trip_dayts.each do |trip_dayt| %>
                <%= link_to dayt_path(trip_dayt.dayt) do %>
                <li class=" my-2 card-height-<%= ((trip_dayt.dayt.duration / 10) * 100).to_i %>">
                  <div style="height: 100%">
                    <div data-paralax-target='card' class="dayt-info card justify-content-around text-center m-1 p-1 lock-card hide">
                      <h2><%= trip_dayt.dayt.title %></h2>
                      <p class="dayt-details p-1">
                        <i class="fa-solid fa-location-dot"></i>
                        <%= trip_dayt.dayt.location %>
                      </p>
                      <%# <div class="location-pos">
                      </div> %>

                      <%# <div class="text-center">
                      </div> %>
                    </div>
                  </div>
                </li>
                <% end %>
              <% end %>


              <%# <li>
                <div class="card align-items-center">
                  <div class="card-body">
                    <p><i class="fa-solid fa-grip-dots-vertical"></i>hello world</p>
                  </div>
                </div>
              </li> %>
            </ul>
          </div>
        </div>

      </div>

      <div class="slidee slidee-map map-top">
        <%= render "shared/hidden_mapbox" %>
      </div>

    </div>

  </div>

  <footer>
    <button class='btn map-btn btn-width' data-action='click->show-hide#toggle'>Map</button>
    <%= button_to "Review", new_trip_mass_review_path(@trip), class:'btn next-btn', method: :get %>
  </footer>
</div>