config/routes.rb
Rails.application.routes.draw do
  # Devise is used for logins & user mangement.
  devise_for :users
  # All page logic it can also be found by running rails routes to see full routing
  root to: 'pages#home'
  get '/journey', to: 'pages#journey', as: 'journey'
  get '/trips/:trip_id/itinerary', to: 'trips#itinerary', as: 'itinerary'
  patch '/trips/:trip_id/update_all', to: 'trip_dayts#update_all', as: "update_all_trip_dayts"
  get '/mydayts', to: 'dayts#mydayts', as: 'mydayts'
  get '/tagged', to: "dayts#tagged", as: :tagged
  patch '/trip_dayt/:id/remove', to: 'trip_dayts#remove', as: 'remove_trip_dayt'
  # get '/dayts/:trip_id', to: 'trip_dayts#save_extended_card', as: 'save_extended_card'

# Nested dayts, trip dayts & mass reviews as they all belong to a trip.
  resources :trips, only: [:new, :create, :show, :update, :index, :destroy] do
    resources :dayts, only: [:index]
    resources :trip_dayts, only: [:create]
    resources :mass_reviews, only: [:new, :create]
  end

  resources :dayts, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :trip_dayts, only: [:delete]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_hidden_mapbox.html.erb
<div style="width: 90%; height: 70%;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_info_window.html.erb
<%= link_to dayt_path(dayt) do %>
  <h2><%= dayt.title %></h2>
  <div class="text_cards">
    <p><i class="fa-solid fa-location-dot">&#8194;</i><%= dayt.location %></p>
    <div class="d-flex">
      <div class="w-50">
        <i class="fa-solid fa-clock">&#8194;</i>&#8194;<%= dayt.duration.to_i %> h
      </div>
      <div class="w-50">
        <i class="fa-solid fa-dollar-sign">&#8194;</i><%= dayt.price > 0 ? "#{dayt.price.to_i} pp" : 'Free' %>&#8194;
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_map_marker.html.erb
<div class = "mapmarker" style = "background-image: url(<%= dayt.photos.first ? cl_image_path(dayt.photos.first.key) : 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80' %>"></div>

app/views/shared/_nav_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-dayt">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "DAYT-thick.png", height: 30 %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Trips", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-dayt">



      <% if current_page?(root_path) %>
        <button class="previous">
          <i class="fa fa-angle-left fa-2x transparent"></i>
        </button>
      <% else %>
        <button onclick="history.go(-1)" class="previous">
          <i class="fa fa-angle-left fa-2x"></i>
        </button>
      <% end %>

    <div class="logo">
      <%= link_to root_path do %>
        <%= image_tag "DAYT-thick.png", class:"dayt-logo" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto text-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Trips", trips_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.key %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

</div>

app/views/shared/_organise.html.erb
<div class="row justify-content-end" id="calendar-container">

  <div class="calendar col-2 d-flex flex-column justify-content-between">
    <p>8am</p>
    <p>9am</p>
    <p>10am</p>
    <p>11am</p>
    <p>12pm</p>
    <p>1pm</p>
    <p>2pm</p>
    <p>3pm</p>
    <p>4pm</p>
    <p>5pm</p>
  </div>

  <div class="col-10">
    <ul data-sortable-target="list" class="h-100" id="hello-list" >
      <i class="fa-regular fa-hand-pointer" data-controller='animate'></i>
      <% @trip_dayts.order(:order).each do |trip_dayt| %>
        <li data-sortable-target="card" data-index-value=<%= trip_dayt.id %> class="my-2 organise card-height-<%= ((trip_dayt.dayt.duration / 10) * 100).to_i %>">
          <div style="height: 100%">
            <div class="dayt-info card justify-content-around text-center m-1 p-1 lock-card " >
              <%= link_to remove_trip_dayt_path(trip_dayt), method: :patch do %>
                <i class='fa-solid fa-xmark'></i>
              <% end %>

              <h2><%= trip_dayt.dayt.title %></h2>
              <p class="dayt-details p-1">
                <i class="fa-solid fa-location-dot"></i>
                <%= trip_dayt.dayt.location %>
              </p>
              <div class="location-pos">
              </div>
              <%# <p class="d-flex dayt-time p-1">
              <i class="fa-solid fa-clock"></i><%= dayt.duration %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>