config/routes.rb
Rails.application.routes.draw do
  # Devise is used for logins & user mangement.
  devise_for :users
  # All page logic it can also be found by running rails routes to see full routing
  root to: 'pages#home'
  get '/journey', to: 'pages#journey', as: 'journey'
  get '/trips/:trip_id/itinerary', to: 'trips#itinerary', as: 'itinerary'
  patch '/trips/:trip_id/update_all', to: 'trip_dayts#update_all', as: "update_all_trip_dayts"
  get '/mydayts', to: 'dayts#mydayts', as: 'mydayts'
  get '/tagged', to: "dayts#tagged", as: :tagged
  patch '/trip_dayt/:id/remove', to: 'trip_dayts#remove', as: 'remove_trip_dayt'
  # get '/dayts/:trip_id', to: 'trip_dayts#save_extended_card', as: 'save_extended_card'

# Nested dayts, trip dayts & mass reviews as they all belong to a trip.
  resources :trips, only: [:new, :create, :show, :update, :index, :destroy] do
    resources :dayts, only: [:index]
    resources :trip_dayts, only: [:create]
    resources :mass_reviews, only: [:new, :create]
  end

  resources :dayts, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :trip_dayts, only: [:delete]

end

app/models/dayt.rb
class Dayt < ApplicationRecord
  # These tags are used for preference selection and can be used to filted out dayts shown to the user. This is made with acts_as_taggable.js library adding functionality.
  TAGS = ["Outdoor", "Indoor", "Brekky", "Lunch", "Dinner", "Nightlife", "Nice Walk", "Art", "Sport", "Music", "Drinks", "Free", "Awesome courses", "Snacks", "Entertainment"]

  belongs_to :user
  acts_as_taggable_on :tags
  has_many :trip_dayts
  has_many :reviews, through: :trip_dayts
  has_many :trips, through: :trip_dayts
  has_many_attached :photos

  # Standard validations for creation of a Dayt
  validates :title, presence: true, length: { minimum: 3 }
  validates :content, presence: true
  validates :duration, presence: true, numericality: true
  validates :location, presence: true
  validates :price, presence: true, numericality: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/controllers/dayts_controller.rb
class DaytsController < ApplicationController

=begin
  A Dayt index is used to select create the stack of cards (Multiple Dayts) that is shown to the user after
  they have selected their preferences tags (Location, Interests, Travel distance & more)
=end

  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    # A trip is created after preferences are confirmed, this is passed in through params
    @trip = Trip.find(params[:trip_id])
    # Dayts selected where not already in the trip, that are near the location & distance, ordered and shown to used
    @dayts = Dayt.where.not(id: @trip.dayts.pluck(:id))
                 .near(@trip.location, @trip.distance)
                 .order(id: :asc)

    # then Dayts are selected if the tags are avialable
    @dayts = @dayts.tagged_with( @trip.tag_list.join(', '), any: true) if @trip.tag_list.any?
    # Reordered and added to a trip.
    @dayts = @dayts.order(id: :asc)
    @trip_dayt = TripDayt.new
    @trip_duration = 0
    @tags = params[:tags]
    # Used for adding up trip_duration bar at the bottom of the page
    
    @trip.trip_dayts.where(status: 'accepted').each { |trip_dayt| @trip_duration += trip_dayt.dayt.duration }
    # Used for mapbox rendering of markers
    @markers = @dayts.geocoded.map do |dayt|
      {
        lat: dayt.latitude,
        lng: dayt.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { dayt: dayt }),
        map_marker: render_to_string(partial: "shared/map_marker", locals: { dayt: dayt })
      }
    end
  end

  def show
    @trip = Trip.find(params[:trip]) if params[:trip]
    @trip_dayt = TripDayt.new

    @dayt = Dayt.find(params[:id])
    # Distance calculations to be shown to the user

    if @trip
      @distance = Geocoder::Calculations.distance_between([@dayt.latitude, @dayt.longitude], [@trip.latitude, @trip.longitude])
    end
    # Mapbox Markers
    @markers =
      [{
        lat: @dayt.latitude,
        lng: @dayt.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { dayt: @dayt }),
        map_marker: render_to_string(partial: "shared/map_marker", locals: { dayt: @dayt })
      }]
      # Open time logic for calculating if AM, PM should be suffixed on time.
    if @dayt.opening_time
      if @dayt.opening_time == 12
        @opening_time = "#{@dayt.opening_time}pm"
      elsif @dayt.opening_time > 12
        @opening_time = "#{@dayt.opening_time - 12}pm"
      else
        @opening_time = "#{@dayt.opening_time}am"
      end
    end

    if @dayt.closing_time
      if @dayt.closing_time == 12
        @closing_time = "#{@dayt.closing_time}pm"
      elsif @dayt.closing_time > 12
        @closing_time = "#{@dayt.closing_time - 12}pm"
      else
        @closing_time = "#{@dayt.closing_time}am"
      end
    end

    #Iterate through each trip_dayt to find matching dayts
    # Select all reviews that have params[:id] == review.trip_dayt.dayt


  end

  def new
    @dayt = Dayt.new
  end

  def create
    @dayt = Dayt.new(dayt_params)
    @dayt.user = current_user
    if @dayt.save
      redirect_to mydayts_path
    else
      render :new
    end
  end

  def destroy
    @dayt = Dayt.find(params[:id])
    @dayt.destroy
    redirect_to mydayts_path
  end

  def mydayts
    @dayts = current_user.dayts
  end

  def edit
    @dayt = Dayt.find(params[:id])
  end

  private

  def dayt_params
    params.require(:dayt).permit(
      :title,
      :content,
      :location,
      :duration,
      :price,
      :opening_time,
      :closing_time,
      :booking_url,
      tag_list: [],
      photos: []
    )
  end
end

app/views/dayts/_added.html.erb
<p>Good</p>

app/views/dayts/_date_test.html.erb
<% @dayts.each do |dayt| %>
  <%= dayt.title %>
  <%= dayt.content %>
  <%= dayt.price %>
  <% dayt.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>
<%= render "mapbox" %>

app/views/dayts/_expanded_dayt.html.erb
<div class='container py-3 expanded'>

  <% if params[:trip] %>
    <%= simple_form_for [@trip, @trip_dayt], html: { class: 'accept-expanded-dayt', data: {controller: 'heart', action: 'submit->heart#fill'} } do |f| %>
      <%= f.hidden_field :dayt_id, value: dayt.id %>
      <%= f.hidden_field :status, value: 'accepted' %>
      <%= f.hidden_field :tags, value: tags %>
      <%= button_tag type: 'submit' do %>
        <i class="fa-regular fa-heart" data-heart-target='heart'></i>
      <% end %>
    <% end %>
  <% end %>

  <% if dayt.photos.size == 1 %>
      <img class="d-block w-100 expanded-photo" src="<%= cl_image_path dayt.photos.first.key %>" alt="photo" >

  <% elsif dayt.photos.size > 1 %>
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% dayt.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= "active" if index.zero? %>">
              <%= cl_image_tag photo.key, class: "d-block w-100 expanded-photo", height: 400, width: 400, crop: :fill %>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>
  <% end %>

  <div class='pt-3 title-expanded' >
    <%= cl_image_tag dayt.user.avatar.key, class: 'avatar-dayt' %>

    <%# Display TAGS ===> %>
    <p>
      <% dayt.tag_list.each do |tag| %>
        <%= link_to tag, tagged_path(tag: tag), class: "badge #{tag_class(tag)}" %>
      <% end %>
    </p>

    <h1 class='exp-title'><%= dayt.title %></h1>
    <% if @dayt.reviews.count.zero? %>
      <p class="me-3 ms-1">No Rating</p>
    <% else %>
      <% @dayt.reviews.average(:rating).round.times do %>
        <i class="fas fa-star"></i>
      <% end %>
    <% end %>
  </div>
  <div class="content-expanded mx-3">
    <div class='d-flex my-3 align-items-center'>
      <div>
        <i class="me-3 ms-1 fa-solid fa-location-dot"></i>
      </div>
      <% if @trip %>
        <%= @distance >= 1 ? "#{@distance.round(1)}km" : "#{(@distance.round(1) * 1000).to_i}m" %> from <%= @trip.location.match(/^\w*/) %>
      <% else %>
        <%= dayt.location %>
      <% end %>
    </div>
    <div class='d-flex my-3'>
      <div class='d-flex align-items-center w-50'>
          <div >
          <i class="me-3 ms-1 fa-solid fa-stopwatch"></i>
          </div>
        <%= dayt.duration.to_i %> h
      </div>
      <% if opening_time && closing_time %>
      <div class='d-flex align-items-center w-50'>
        <div>
        <i class="me-3 ms-1 fa-solid fa-calendar"></i>
        </div>
        <%= opening_time%> - <%= closing_time %>
      </div>
      <% end %>
    </div>

    <div class="d-flex">
      <div class='d-flex w-50'>
          <div>
          <i class="me-3 ms-1 fa-solid fa-dollar"></i>
          </div>
        <%= dayt.price.to_i > 0 ? dayt.price.to_i : 'Free' %>
      </div>
      <%= link_to 'Visit website', dayt.booking_url, target: "_blank", class: 'w-50 link-booking' if dayt.booking_url %>
    </div>

    <div class="py-4 text-expanded">
    <%= dayt.content %>
    </div>
  </div>


  <%= render 'mapbox' %>
</div>

app/views/dayts/_form.html.erb
<%= simple_form_for dayt do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :location,
            input_html: { data: { address_target: "location" }, class: "d-none" },
            wrapper_html: { data: { controller: "address", address_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :duration %>
  <%= f.input :price %>

  <div class="mb-3 optional dayt_opening_time">
    <label for="opening_time" class="form-label">Opening time</label>
    <select class="form-control optional" name="opening_time" id="opening_time">
      <option value="">Select</option>
      <option value="1">1am</option>
      <option value="2">2am</option>
      <option value="3">3am</option>
      <option value="4">4am</option>
      <option value="5">5am</option>
      <option value="6">6am</option>
      <option value="7">7am</option>
      <option value="8">8am</option>
      <option value="9">9am</option>
      <option value="10">10am</option>
      <option value="11">11am</option>
      <option value="12">12pm</option>
      <option value="13">1pm</option>
      <option value="14">2pm</option>
      <option value="15">3pm</option>
      <option value="16">4pm</option>
      <option value="17">5pm</option>
      <option value="18">6pm</option>
      <option value="19">7pm</option>
      <option value="20">8pm</option>
      <option value="21">9pm</option>
      <option value="22">10pm</option>
      <option value="23">11pm</option>
      <option value="24">12am</option>
    </select>
  </div>

  <div class="mb-3 optional dayt_closing_time">
    <label for="closing_time" class="form-label">Closing time</label>
    <select class="form-control optional" name="closing_time" id="closing_time">
      <option value="">Select</option>
      <option value="1">1am</option>
      <option value="2">2am</option>
      <option value="3">3am</option>
      <option value="4">4am</option>
      <option value="5">5am</option>
      <option value="6">6am</option>
      <option value="7">7am</option>
      <option value="8">8am</option>
      <option value="9">9am</option>
      <option value="10">10am</option>
      <option value="11">11am</option>
      <option value="12">12pm</option>
      <option value="13">1pm</option>
      <option value="14">2pm</option>
      <option value="15">3pm</option>
      <option value="16">4pm</option>
      <option value="17">5pm</option>
      <option value="18">6pm</option>
      <option value="19">7pm</option>
      <option value="20">8pm</option>
      <option value="21">9pm</option>
      <option value="22">10pm</option>
      <option value="23">11pm</option>
      <option value="24">12am</option>
    </select>
  </div>

  <%= f.input :booking_url %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= render 'layouts/tags', f: f %>
  <footer>
    <%= f.submit 'Updayt', class: "btn next-btn" %>
  </footer>
<% end %>

app/views/dayts/_mapbox.html.erb
<div style="width: 100%; height: 300px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/dayts/_slide.html.erb
<%# REMOVE CARD button ' X ' ========= > %>
<div class="swiper-slide" data-controller="trip-dayt" data-action='click->swiper#index'>
  <% trip_dayt =  TripDayt.new %>
  <%= simple_form_for [trip, trip_dayt],
    html: {
    class: 'decline',
    data: { action: "submit->trip-dayt#create submit->swiper#move" }
    } do |f| %>
      <%= f.hidden_field :dayt_id, value: dayt.id  %>
      <%= f.hidden_field :status, value: 'declined' %>
      <button data-trip-dayt-target='declineButton'><i class="fas fa-regular fa-xmark" data-trip-dayt-target='declineIcon'></i></button>
    <% end %>

<%# ADD CARD button ' heart ' ========= > %>
    <%= simple_form_for [trip, trip_dayt],
    html: {
    class: 'accept',
    data: { action: "submit->trip-dayt#create submit->swiper#move" }
    } do |f| %>
      <%= f.hidden_field :dayt_id, value: dayt.id %>
      <%= f.hidden_field :status, value: 'accepted' %>
      <button data-trip-dayt-target='acceptButton'><i class="fa-regular fa-heart" data-trip-dayt-target='acceptIcon'></i></button>
  <% end %>

<%# PHOTOS card swipper ========= > %>
<%= link_to dayt_path(dayt, trip: trip), data_action: 'click->swiper#index' do %>
  <%= cl_image_tag dayt.photos.first.key %>


<%# CARD TEXT infos ========= > %>
  <div class="card-blue d-flex flex-column justify-content-between text-center">

      <h2><%= dayt.title %></h2>

<%# RATINGS stars or ' No rating ' ========= > %>
 <div class="d-inline p2 rating_star_style">
    <% if dayt.reviews.count.zero? %>
          <p>No Rating yet ...</p>
        <% else %>
          <% dayt.reviews.average(:rating).round.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <% end %>
 </div>

<%# TIME + PRICE ========= > %>
        <div class="d-flex justify-content-around">

          <div>
            <i class="fa-solid fa-stopwatch icon_card">&#8194;</i>
            <p class="card_text_content"><span data-trip-dayt-target='duration'><%= dayt.duration.to_i %></span>&#8194;h</p>
          </div>


          <div>
            <i class="fa-solid fa-dollar-sign icon_card">&#8194;</i>
            <p class="card_text_content"><%= dayt.price > 0 ? "#{dayt.price.to_i} pp" : 'Free' %>&#8194;</p>
          </div>
        </div>


<%# DISTANCE location ========= > %>
          <i class="fa-solid fa-location-dot icon_card">&#8194;</i>
          <% distance = Geocoder::Calculations.distance_between([dayt.latitude, dayt.longitude], [trip.latitude, trip.longitude]) %>
          <p class="card_text_content"><%= distance >= 1 ? "#{distance.round(1)}km" : "#{(distance.round(1) * 1000).to_i}m" %> from <%= trip.location.match(/^\w*/) %></p>

    </div>

      <% end %>

</div>

app/views/dayts/edit.html.erb
<div class="container padding-bottom">
  <h1 class="text-center pt-3">Edit Dayt</h1>
  <%= render 'form', dayt: @dayt %>
</div>

app/views/dayts/index.html.erb
<div data-controller='show-hide' class='bg-index'>
  <div class="slider-container" >
    <div class="slider" data-show-hide-target="slider">

      <div class="slidee">
        <div class="text-background">
          <h3>Out of dayts...</h3>
          <h3>Press next to organise</h3>
        </div>
        <h1 class="text-center pt-3">Add Dayts to your Trip</h1>
        <div class="swiper" data-controller='swiper'>
          <div class="swiper-wrapper">
            <% @dayts.first(6).each do |dayt|  %>

              <%= render 'slide', dayt: dayt, trip: @trip %>

            <% end %>
          </div>
        </div>
      </div>

      <div class="slidee slidee-map">
        <%= render "shared/hidden_mapbox" %>
      </div>

    </div>
  </div>


  <footer>
    <button class='btn map-btn btn-width' data-action='click->show-hide#toggle'>Map</button>
    <%= link_to "Next", itinerary_path(@trip), class: "btn next-btn btn-width" %>
  </footer>
</div>

<div class="progress shadow-lg">
  <div role="progressbar" class="progress-bar
  <%= 'bg-warning' if @trip_duration * 12.5 >= 70 %>"
   style="width: <%= @trip_duration * 12.5 %>%">
    <div><span id='time-added'><%= @trip_duration.to_i %></span>h</div>
  </div>

  <% if @trip_duration.to_i < 8 %>
  <div class="w-100 d-flex justify-content-end pe-1 time-left"><span id='time-left'><%= 8 - @trip_duration.to_i %></span>h to go</div>
  <% end %>
</div>

app/views/dayts/mydayts.html.erb
<div class="container px-4 padding-bottom">
  <h1 class="text-center pt-3 m-0">My Dayts</h1>
  <% if @dayts.empty? %>
    <h3 class='text-notice'>
      Looks like theres nothing here, select create a dayt to get started!
    </h3>
  <% end %>

  <% @dayts.each do |dayt| %>
    <%= link_to dayt_path(dayt), class: 'trip-link' do %>
    <div class="card-trip shadow" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dayt.photos.first ? dayt.photos.first.url : 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1635&q=80' %>)">
      <h3><%= dayt.title %></h3>
      <%= link_to dayt_path(dayt),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
      <%= link_to edit_dayt_path(dayt) do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>
  <footer>
    <%= link_to 'New Dayt', new_dayt_path, class: "btn next-btn" %>
  </footer>

app/views/dayts/new.html.erb
<div class="container padding-bottom">
  <h1 class="text-center pt-3">New Dayt</h1>
  <%= render 'form', dayt: @dayt %>
</div>

app/views/dayts/show.html.erb
<%= render 'expanded_dayt', dayt: @dayt, opening_time: @opening_time, closing_time: @closing_time, tags: @tags %>