config/routes.rb
Rails.application.routes.draw do
  # Devise is used for logins & user mangement.
  devise_for :users
  # All page logic it can also be found by running rails routes to see full routing
  root to: 'pages#home'
  get '/journey', to: 'pages#journey', as: 'journey'
  get '/trips/:trip_id/itinerary', to: 'trips#itinerary', as: 'itinerary'
  patch '/trips/:trip_id/update_all', to: 'trip_dayts#update_all', as: "update_all_trip_dayts"
  get '/mydayts', to: 'dayts#mydayts', as: 'mydayts'
  get '/tagged', to: "dayts#tagged", as: :tagged
  patch '/trip_dayt/:id/remove', to: 'trip_dayts#remove', as: 'remove_trip_dayt'
  # get '/dayts/:trip_id', to: 'trip_dayts#save_extended_card', as: 'save_extended_card'

# Nested dayts, trip dayts & mass reviews as they all belong to a trip.
  resources :trips, only: [:new, :create, :show, :update, :index, :destroy] do
    resources :dayts, only: [:index]
    resources :trip_dayts, only: [:create]
    resources :mass_reviews, only: [:new, :create]
  end

  resources :dayts, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :trip_dayts, only: [:delete]

end

app/views/layouts/_card.html.erb
<div class="container justify-content-center">
  <div class="row>">
    <div class="card" style="width: 18rem;">
      <img src="#" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-copyright">
  <a href="https://github.com/hwalk1/dayt_app"><i class="fab fa-github"></i></a>Made with <i class="fas fa-heart"></i> by Aren, Hayden, Lea, and Michael.
</div>

app/views/layouts/_home_selection_cards.html.erb
<%# ========== TOURIST / LOCAL home cards ============= %>
<div class="home_text">
  <h1 class="pt-3">I am a ...</h1>
</div>

<div class="home_cards">

  <div class="banner tourist_card" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dmcsijvtd/image/upload/v1655298030/development/00alien_planet_june22_dl5wfl.jpg);">
    <div>
      <%= link_to "Traveler", new_trip_path,
        :class => "waves full-btn btn-big", :method => :get %>
    </div>
  </div>

  <div class="banner local_card" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dmcsijvtd/image/upload/v1655429415/development/alienhouse1122_nr0pza.jpg);">
    <div>
      <%= link_to "Local", mydayts_path,
        :class => "waves full-btn btn-big", :method => :get %>
    </div>
  </div>
</div>

app/views/layouts/_tags.html.erb
<%= f.input :tag_list, label: ' ',
    as: :check_boxes,
    input_html: { class: "tag-selector" },
    item_wrapper_class: 'tag-item waves-flat',
    collection: Dayt::TAGS,
    include_hidden: false %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag %>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body data-controller='waves'>
    
    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <%# render 'shared/organise' %>     <%# this is to test sortablejs  %>
  <script src="https://kit.fontawesome.com/7b8fdf30c4.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </body>
</html>